apiVersion: v1
kind: Service
metadata:
  name: boot001ser
spec:
  type: NodePort
  ports:
  - port: 8001
    targetPort: 7777
    protocol: TCP
    # 외부에서 접근하는 포트(워커 노드 내에서 30001번으로 띄워져 있다.)
    nodePort: 30001
  selector:
    app: boot001kube