server:
  port: 8000


spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: 1st-service-get
#          uri: http://localhost:62165/
          uri: lb://1ST-SERVICE # ?? ???? ??
          predicates:
            - Path=/first-service/**
          filters:
          # ???? ??? ?? ??????? ??? ??? ???? ?? ??? ???? ??
          # ?????? ?????? ???? ??? ??? ????.
            - RewritePath=/first-service/(?<segment>.*), /$\{segment}

        - id: 2nd-service-get
          uri: lb://2ND-SERVICE
          predicates:
            - Path=/second-service/**
          filters:
            - RewritePath=/second-service/(?<segment>.*), /$\{segment}
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
