server:
  port: 8761
eureka:
  clinet:
    # eureka server? eureka server?? ???? ??? ??? ??.
    register-with-eureka: false

    # eureka server? ?? microservice?? ?????(30???) ???? ??? ??? ??.
    fetch-regitry: false